### ISSUE TITLE
A proposal for a format for metric expressions

### ISSUE THREAD

**Issue by apannetrat** [cloudsecurityalliance/continuous-audit-metrics#3]
Within the YAML metrics catalog, we need a common agreement on the formula used for the description of the mathematical formula of a metric. In most cases, this formula is simply `100 * A/B` and most readers will understand what this means when A and B are further specified in the description of the metric.

For example, the expression of a metric might look like this:
```yaml
  expression:
    result: "Percentage of compliant code"
    formula: "100 * A/B"
    variables:
      - name: A
        description: Total number of pieces of production code that have an associated verification step
      - name: B
        description: Total number of pieces of production code
```

To make things a bit more formal, I propose that the `formula` is defined as a string that uses a very restricted subset of Javascript expressions as defined by the following grammar (this will look familiar to programmers of many modern languages).

```
​   Expr:
       ​Literal
       ​Identifier
       ​Expr "&&" Expr
       ​Expr "||" Expr
       ​Expr "<" Expr
       ​Expr "<=" Expr
       ​Expr ">" Expr
       ​Expr ">=" Expr
       ​Expr "!=" Expr
       ​Expr "==" Expr
       ​Expr "+" Expr
       ​Expr "-" Expr
       ​Expr "/" Expr
       ​Expr "*" Expr
       ​Expr "%" Expr
       ​"-" Expr
       ​"!" Expr
       ​"(" Expr ")"
       ​FunctionCall

   ​Literal:
       ​StringLiteral
       ​NumericLiteral
       ​ArrayLiteral
       ​ObjectLiteral
       ​"true"
       ​"false"
       ​"null"

   ​Identifier:
       ​IdentifierName
       ​Identifier "[" Expr "]"
       ​Identifier "." IdentifierName

   ​FunctionCall:
       ​Identifier "(" ")"
       ​Identifier "(" ParameterList ")"

   ​ParameterList:
       ​Expr
       ​ParameterList "," Expr

   ​ObjectLiteral:
       ​"{" "}"
       ​"{" ObjectElements "}"

   ​ArrayLiteral:
       ​"[" "]"
       ​"[" ArrayElements "]"

   ​ArrayElements:
       ​Expr
       ​ArrayElements "," Expr

   ​ObjectElements:
       ​ObjectElementItem
       ​ObjectElements, ObjectElementItem

   ​ObjectElementItem:
       ​IdentifierName ":" Expr
       ​StringLiteral ":" Expr
```

Furthermore, we can specify that all operators (e.g. ||, &&, *, + etc.) behave as defined in ECSMAscript version 5.1 (see https://262.ecma-international.org/5.1/). This means that any javascript engine would be capable of processing these expressions if needed.

Function names and variable names would be further specified in the description of the metric. For example, if we need a function `max(a,b)` which returns the maximum of `a` and `b` we would simply explain that in the metric description.
